version: '3.7'
services:
    postgres:
        image: postgres:15.2-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=spin_dev
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          # - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
